[tool.isort]
profile = "black"

[tool.black]
line-length = 100

[tool.pytest.ini_options]
minversion = "2.0"
addopts = """
  -rfEX -p pytester --strict-markers --verbosity=3
  """
env = [
    "CRATEDB_CONNECTION_STRING=crate://crate@localhost/?ssl=false&schema=testdrive",
    "CRATEDB_PROMETHEUS_ADAPTER_METRICS_URL=http://localhost:9268/metrics",
    "PROMETHEUS_URL=http://localhost:9090",
]

log_level = "DEBUG"
log_cli_level = "DEBUG"

testpaths = [
    "tests",
]
xfail_strict = true
markers = [
]
